Repository ace-design/jpipe, pull requests merged in 2023-11, with the labels that each got.

#44 Pattern Implementation Code: Unbuilding Diagrams
  src/main/java/ca/mcscert/jpipe/compiler/ModelCreationListener.java
  src/main/java/ca/mcscert/jpipe/compiler/builders/ConcreteJustificationBuilder.java
  src/main/java/ca/mcscert/jpipe/compiler/builders/ImplementJustificationBuilder.java
  src/main/java/ca/mcscert/jpipe/compiler/builders/JustificationPatternBuilder.java
  src/main/java/ca/mcscert/jpipe/compiler/builders/ScopedContextBuilder.java
  src/main/java/ca/mcscert/jpipe/model/justification/Conclusion.java
  src/main/java/ca/mcscert/jpipe/model/justification/ConcreteJustification.java
  src/main/java/ca/mcscert/jpipe/model/justification/JustificationElement.java
  src/main/java/ca/mcscert/jpipe/model/justification/Strategy.java
  src/main/java/ca/mcscert/jpipe/model/justification/SubConclusion.java
  src/main/java/ca/mcscert/jpipe/model/justification/Support.java
  src/main/java/ca/mcscert/jpipe/visitors/UnBuilder.java
  src/test/resources/pattern_declaration.jd
  src/test/resources/patterns.jd
  src/test/resources/with_impl.jd
Labels: feature

#55 specify log level from cli #45
  src/main/java/Main.java
  src/main/java/ca/mcscert/jpipe/CommandLineConfiguration.java
  src/main/java/ca/mcscert/jpipe/Logo.java
Labels: refactor, maintenance

#50 POM maintenance (Fall edition)
  .github/workflows/ci.yml
  pom.xml
Labels: maintenance

#53 Syntax for composition unit
  src/main/antlr4/ca/mcscert/jpipe/syntax/JPipe.g4
  src/main/java/ca/mcscert/jpipe/compiler/CompositionError.java
  src/main/java/ca/mcscert/jpipe/compiler/ModelCreationListener.java
  src/main/java/ca/mcscert/jpipe/compiler/builders/MergeBuilder.java
  src/main/java/ca/mcscert/jpipe/operators/MergeOperator.java
  src/main/java/ca/mcscert/jpipe/operators/NaryOperator.java
  src/test/resources/composition.jd
Labels: feature, LANGUAGE
